### PR TITLE
Fix fetching server version for configured bundle path

### LINKED ISSUE #671: Support custom bundle gemfile when checking server version for telemetry
### Operating System

macOS 13.4.1 (22F82)

### Ruby version

2.7.4

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rvm

### Description

Extension fails to activate if ruby-lsp is not included in root `Gemfile` or no `.ruby-lsp/Gemfile` is present, which is a legit scenario when `"rubyLsp.bundleGemfile"` is set to a custom path.

I worked this around by adding a hacky `.ruby-lsp/Gemfile`:
```ruby
eval_gemfile(File.expand_path("../local_gems/Gemfile", __dir__))
gem "debug", require: false, group: :development, platforms: :mri, source: "https://rubygems.org"
```
Where `local_gems/Gemfile` is the same value I set for `"rubyLsp.bundleGemfile"`.

### PR DESCRIPTION
**Pull request by vinistock**
### Motivation

Closes #671

If the user has configured a custom Gemfile outside of the project, then we need to use that to check the version of the server.

### Implementation

Added another check to define the correct `bundleGemfile` to use.

### CODE REVIEW

File: src/client.ts [hunk 1]
```diff
@@ -624,8 +624,17 @@ export default class Client implements ClientInterface {
 
   private async getServerVersion(): Promise<string> {
     let bundleGemfile;
-
-    if (fs.existsSync(path.join(this.workingFolder, ".ruby-lsp", "Gemfile"))) {
+    const customBundleGemfile: string = vscode.workspace
+      .getConfiguration("rubyLsp")
+      .get("bundleGemfile")!;
+
+    // If a custom Gemfile was configured outside of the project, use that. Otherwise, prefer our custom bundle over the
```
Comment (bitwise-aiden) [inline src/client.ts:631]: > configured outside of the project

Is this at odds with using `. getConfiguration("rubyLsp")`?

Comment (vinistock) [reply src/client.ts:631]: No, by outside the project we mean outside of the current working directory. Some users like to have a separate `Gemfile` only for development dependencies and we provide this configuration as a way to point to it.

For example, something like this
```shell
# Regular bundle
project/Gemfile

# Ruby LSP custom bundle
project/.ruby-lsp/Gemfile

# User configured custom bundle
~/some/other/path/outside/of/project/Gemfile
```

**Review by KaanOzkan — APPROVED** [review]

**Review by bitwise-aiden — APPROVED** [review]
